### ISSUE TITLE
[Question] How to deal with a refDoc like a model?

### ISSUE THREAD

**Issue by RezaOwliaei** [fogine/couchbase-odm#27]
Hi @fogine 
Is it a good practice to add some props to refDocs?
If so, would you please give a sample code how to do this?

## What you are doing?
I'm looking for a clean solution to store user's secrets, not in the user model, but something like this:
```
user_123
  - _id:123
  - username: johnsmith
  - firstname: john
  - lastname: smith
  - someOtherMeta: ...
```
```
secret_user_123
  - pass: ...
  - otp: ...
  - aSecretToken: ...
 - emailVerficationCode: ...
 - mobileVerificationCode: ...
 - security:
    - question: ...
   - password: ...
```
This way, I should be able to fetch a user secret, when needed, just by having the user key:

```
getSecretByUser(user._id)
```

If the `refDoc` isn't a proper way, your recommendation is highly appreciated.
